first review
Jobret019/Dicom_file_corrector pull request #2
Opened 2023-07-28 15:05 UTC by Jobret019

2023-08-06 15:28 UTC, smichi23 commented on dicom_file_corrector/utils/point_cloud_array_creator.py
> +def flip_image_point_cloud(image_cloud: np.array) -> np.array:
peut-être z_flip_image_point_cloud pour pas que les users pensent qu'ils peuvent flipper dans tous les axes

2023-08-06 15:29 UTC, smichi23 commented on dicom_file_corrector/utils/point_cloud_array_creator.py
> +def image_point_cloud(path_to_serie: str) -> np.array:
create_image_point_cloud_from_dicom_series_folder peut-être?

2023-08-06 15:30 UTC, smichi23 commented on dicom_file_corrector/utils/point_cloud_array_creator.py
> +    points_coordinate = []
Normalement les variables ne devraient pas avoir de lettre majuscule. Seulement les classes

2023-08-06 15:32 UTC, smichi23 commented on dicom_file_corrector/utils/point_cloud_array_creator.py
> +    pixel_positions_x,pixel_positions_y,_ = pixel_position_in_patient_coordinate(os.path.join(path_to_serie,paths[0]))
Toujours un espace après les virgules. Ce commentaire s'applique partout

2023-08-06 15:46 UTC, smichi23 commented on dicom_file_corrector/utils/point_cloud_array_creator.py
> +        maximum_HU_pixels_indexs = np.where(data == max)
Tous les maximums on exactement la même valeur? Et tous les maximums sont associés à des sources et non à autre chose?

2023-08-06 15:47 UTC, smichi23 commented on dicom_file_corrector/utils/point_cloud_array_creator.py
> +    """
create_source_point_cloud_from_RTPLAN?

2023-08-06 15:49 UTC, smichi23 commented on dicom_file_corrector/utils/point_cloud_array_creator.py
> +def image_hu_data(path_to_image_file: str) -> np.array:
get_image_hu_data_from_file()

2023-08-06 15:50 UTC, smichi23 commented on dicom_file_corrector/utils/point_cloud_array_creator.py
> +def flip_image_point_cloud(image_cloud: np.array) -> np.array:
Il est bonne protique de commencer les nom de méthode par des verbes, puisqu'elles font des actions

2023-08-06 15:50 UTC, smichi23 commented on dicom_file_corrector/utils/point_cloud_array_creator.py
> +def pixel_position_in_patient_coordinate(path_to_image_file: str) -> tuple[list,list,float]:
Non avec verbe

2023-08-06 15:51 UTC, smichi23 commented on dicom_file_corrector/utils/point_cloud_array_creator.py
> +    rangee = open_dicom.Rows
Essaye de garder tes variables dans une même langue hahah

2023-08-06 15:52 UTC, smichi23 commented on dicom_file_corrector/utils/point_cloud_array_creator.py
> +    deltai,deltaj=pixel_spacing[0],pixel_spacing[1]
Mettre des espaces autour des égals. Commentaire s'applique sur tout le code. Il est important de suivre le pep8 (sous ligné gris dans pycharm)

2023-08-06 15:54 UTC, smichi23 commented on dicom_file_corrector/utils/point_cloud_array_creator.py
> +def source_position_in_patient_coordinate(path_to_plan: str, setup_number: int) -> np.array:
Verbe

2023-08-06 15:55 UTC, smichi23 commented on dicom_file_corrector/utils/point_cloud_array_creator.py
> +            source_position_2 = None
Pas besoin de faire de changement, mais en général, il est bonne pratique de produire des logs quand tes méthodes retourne des None. Comme ça le gens savent pourquoi il reçoive None

2023-08-06 15:56 UTC, smichi23 commented on dicom_file_corrector/utils/visualisation_of_point_cloud.py
> +def graphe_nuage_point(data_point_cloud: np.array) -> None:
Consistent avec la langue et verbe

2023-08-06 16:00 UTC, smichi23 commented on dicom_file_corrector/utils/visualisation_of_point_cloud.py
> +def superposed_point_cloud(data_point_cloud_1: np.array, data_point_cloud_2: np.array,
Ça c'est des belles fonctions! Ça vaut toujours la peine de faire des fonctions pour faire des graphs. À un certain point, une seule méthode peux produire plusieurs sorte de graphique! ETK c'est une bonne pratique à avoir

2023-08-06 16:05 UTC, smichi23 commented on dicom_file_corrector/uid_changer.py
> +def generate_uid(entropy_sources: Optional[List[str]] = None) -> pydicom.uid.UID:
Ça passe puisque tu avais de la difficulté à l'installer , mais ils serait bien de l'importer via pip install. Il est désormais public via PYGRPM. Ça sera ptête plus facile de l'installer par la (tu peux demander à Ronan si tu veux de l'aide en personne)

2023-08-06 16:07 UTC, smichi23 commented on dicom_file_corrector/uid_changer.py
> +
Très bien ici! Faudrait juste que je regarde les DICOMs finaux pour valider que le tout suit le standard!

2023-08-06 16:09 UTC, smichi23 commented on dicom_file_corrector/patient_folder_info_extractor.py
> +def series_paths_from_patient_folder(path_to_patient: str) -> dict:
Verbe (voir autre commentaires pour comprendre)

2023-08-06 16:10 UTC, smichi23 commented on dicom_file_corrector/patient_folder_info_extractor.py
> +    """
Verbe (voir autre commentaires pour comprendre)

2023-08-06 16:10 UTC, smichi23 commented on dicom_file_corrector/patient_folder_info_extractor.py
> +    """
Verbe (voir autre commentaires pour comprendre)

2023-08-06 16:11 UTC, smichi23 commented on dicom_file_corrector/main.py
> +import patient_folder_info_extractor
I guess que c'est à  venir right?

2023-08-06 16:12 UTC, smichi23 commented on dicom_file_corrector/folder_of_patient_info_extractor.py
> +    """
Verbe (voir autre commentaires pour comprendre)

2023-08-06 16:12 UTC, smichi23 commented on dicom_file_corrector/folder_of_patient_info_extractor.py
> +    """
Verbe (voir autre commentaires pour comprendre)

2023-08-06 16:14 UTC, smichi23 commented on dicom_file_corrector/folder_of_patient_info_extractor.py
> +import utils.point_cloud_array_creator as pc
Peut-être as cloud_creater pour faciliter la lecture

2023-08-06 16:17 UTC, smichi23 commented on dicom_file_corrector/file_and_folder_corrector.py
> +    open_image.ImageComments = 'The Image Position (Patient) was corrected with an inversion in z and then a shift of '+string_x_translation+' in x, '+string_y_translation+' in y and '+string_z_trans
Le commentaire pourrait être un argument à ta fonction, ça serait un peu plus flexible.

2023-08-06 16:18 UTC, smichi23 commented on dicom_file_corrector/file_and_folder_corrector.py
> +    :param path_to_RTDOSE : the path of the RTDOSE Dicom file
Ça serait pas plus removing DVHSequence plutôt que de créer un autre DICOM?

2023-08-06 16:20 UTC, smichi23 commented on dicom_file_corrector/file_and_folder_corrector.py
> +    open_structure.StructureSetDescription = 'All the contours in these structures were corrected with an inversion and then a shift of '+string_z_translation+ ' in z with an ICP algorithm. GIT : htt
Le commentaire pourrait être un argument à ta fonction, ça serait un peu plus flexible.

2023-08-06 16:22 UTC, smichi23 commented on dicom_file_corrector/file_and_folder_corrector.py
> +    order_of_series_reading=[0,3,1,2]
MMm, ça semble très dépendant des données. Peut-être utiliser une méthode plus robuste ou avoir ce paramètre en argument et bien décrire la tâche de l'utilisateur pour ce paramètre

2023-08-06 16:25 UTC, smichi23 commented on dicom_file_corrector/Iterative_closest_point.py
> +
Ce n'est pas un code que tu peux import au lieu de copy paste? S'il y a des updates, tu pourrait aussi en profiter!

2023-08-06 16:26 UTC, smichi23 requested changes
C'est quand même bien!

2023-08-07 12:26 UTC, Jobret019 commented on dicom_file_corrector/main.py
> +import patient_folder_info_extractor
exact !

2023-08-07 12:51 UTC, Jobret019 commented on dicom_file_corrector/file_and_folder_corrector.py
> +    order_of_series_reading=[0,3,1,2]
Je suis d'accord que ça dépend beaucoup des données, mais il faut respecter l'ordre suivant de correction : image, struct, dose, plan ou image, struct, plan, dose car la struct réfère aux images du CT et les rtdose et rtplan réfère au rtstruct. Si je veux tout faire one shot, je dois suivre cette ordre. Je vais quand même patenter pour que ce soit un peu moins dépendant des données !

2023-08-07 15:36 UTC, Jobret019 commented on dicom_file_corrector/Iterative_closest_point.py
> +
J'ai essayé, mais ça me dit que ce n'est pas un projet python ?

2023-08-07 15:48 UTC, Jobret019 commented on dicom_file_corrector/file_and_folder_corrector.py
> +    open_image.ImageComments = 'The Image Position (Patient) was corrected with an inversion in z and then a shift of '+string_x_translation+' in x, '+string_y_translation+' in y and '+string_z_trans
Je suis d'accord, mais je ne sais pas comment je pourrais l'intégrer en argument sachant que si on veut mettre les translations, il faut faire plusieurs partis de string (exemple ici on a 4 parties).

2023-08-10 14:59 UTC, merged